import crypto from 'node:crypto'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import AdmZip from 'adm-zip'
import { extractTableauAst } from '../scripts/extract-tableau-ast.mjs'
import { compareAsts, toCsv } from '../scripts/compare-asts.mjs'

const jobs = new Map()
const packages = new Map()

function safeName(value = 'ConvertedReport') {
  return String(value)
    .replace(/[^a-zA-Z0-9 _-]+/g, '')
    .trim()
    .replace(/\s+/g, ' ') || 'ConvertedReport'
}

function daxFromTableauFormula(expression = '') {
  return String(expression)
    .replace(/\[([^\]]+)\]/g, (_, field) => `'Tableau Extract'[${field}]`)
    .replace(/MAKEDATE\(([^,]+),([^,]+),([^\)]+)\)/gi, 'DATE($1,$2,$3)')
    .replace(/DATEDIFF\('([^']+)'\s*,\s*([^,]+),\s*([^\)]+)\)/gi, 'DATEDIFF($2,$3,$1)')
}

function createModelDefinition(tableauAst) {
  const dataSources = tableauAst.nodes.filter((node) => node.kind === 'data_source')
  const calculations = tableauAst.nodes.filter((node) => node.kind === 'calculation')
  const primaryFields = Array.from(new Set(dataSources.flatMap((source) => source.fields || []))).slice(0, 80)

  return {
    name: safeName(tableauAst.workbook.name),
    compatibilityLevel: 1567,
    model: {
      culture: 'en-US',
      dataAccessOptions: {
        legacyRedirects: true,
        returnErrorValuesAsNull: true,
      },
      tables: [
        {
          name: 'Tableau Extract',
          description: 'Generated table placeholder from Tableau AST. Replace source expression with the actual Power Query import.',
          columns: primaryFields.map((field) => ({
            name: field,
            dataType: 'string',
            sourceColumn: field,
            summarizeBy: 'none',
          })),
          partitions: [
            {
              name: 'Tableau Extract',
              mode: 'import',
              source: {
                type: 'm',
                expression: ['let', '    Source = #table({}, {})', 'in', '    Source'].join('\n'),
              },
            },
          ],
          measures: calculations.map((calculation) => ({
            name: safeName(calculation.name),
            expression: daxFromTableauFormula(calculation.expression),
            formatString: 'General',
            description: `Generated from Tableau formula: ${calculation.expression}`,
          })),
        },
      ],
    },
  }
}

function createReportDefinition(tableauAst) {
  const visuals = tableauAst.nodes.filter((node) => node.kind === 'visual')
  return {
    version: '4.0',
    pages: [
      {
        name: 'ReportSection',
        displayName: 'Converted Tableau Views',
        visuals: visuals.map((visual, index) => ({
          name: `visual_${index + 1}`,
          displayName: visual.name,
          visualType: visual.visual_type || 'table',
          position: {
            x: (index % 2) * 640,
            y: Math.floor(index / 2) * 360,
            width: 600,
            height: 320,
          },
          source: visual,
        })),
      },
    ],
  }
}

function powerBiAstFromTableau(tableauAst) {
  return {
    workbook: {
      name: tableauAst.workbook.name,
      target_file: `${safeName(tableauAst.workbook.name)}.pbip`,
      format: 'powerbi-project',
      generated_by: 'altimate-ai-powerbi-ast-placeholder',
      ast_version: '0.1.0',
    },
    nodes: tableauAst.nodes.map((node) => ({ ...node, source_kind: node.kind, generated_from: 'tableau_ast' })),
  }
}

function addJson(zip, filePath, value) {
  zip.addFile(filePath, Buffer.from(`${JSON.stringify(value, null, 2)}\n`, 'utf8'))
}

function createPbipPackage({ jobId, originalName, tableauAst, powerbiAst, validationCsv }) {
  const projectName = safeName(tableauAst.workbook.name)
  const root = `${projectName}.PowerBIProject`
  const migrationSpec = {
    job_id: jobId,
    original_file: originalName,
    generated_at: new Date().toISOString(),
    status: 'pbip-generated',
    pbip_path: `${root}/${projectName}.pbip`,
    next_steps: [
      'Open the generated .pbip file in Power BI Desktop.',
      'Review generated DAX measures, source queries, and report layout.',
      'Replace placeholder Power Query source with the real data source.',
      'Save as .pbix from Power BI Desktop or configure GitHub Actions packaging.',
    ],
  }

  const zip = new AdmZip()
  addJson(zip, 'tableau_ast.json', tableauAst)
  addJson(zip, 'powerbi_ast.json', powerbiAst)
  zip.addFile('validation_results.csv', Buffer.from(validationCsv, 'utf8'))
  addJson(zip, 'migration_spec.json', migrationSpec)
  zip.addFile('README.txt', Buffer.from('Power BI PBIP project package generated by Altimate Migrator.\n', 'utf8'))
  addJson(zip, `${root}/${projectName}.pbip`, {
    version: '1.0',
    artifacts: [
      { report: { path: `./${projectName}.Report` } },
      { semanticModel: { path: `./${projectName}.SemanticModel` } },
    ],
  })
  addJson(zip, `${root}/${projectName}.Report/definition.pbir`, {
    version: '4.0',
    datasetReference: { byPath: `../${projectName}.SemanticModel` },
  })
  addJson(zip, `${root}/${projectName}.Report/report.json`, createReportDefinition(tableauAst))
  addJson(zip, `${root}/${projectName}.SemanticModel/definition.pbism`, { version: '1.0' })
  addJson(zip, `${root}/${projectName}.SemanticModel/definition/model.bim`, createModelDefinition(tableauAst))
  addJson(zip, `${root}/powerbi_ast.json`, powerbiAst)
  zip.addFile(`${root}/README.md`, Buffer.from(`# ${projectName} Power BI Project\n\nOpen the .pbip in Power BI Desktop, review, then save as .pbix.\n`, 'utf8'))
  return { buffer: zip.toBuffer(), migrationSpec }
}

function absoluteUrl(request, relativePath) {
  const baseUrl = process.env.PUBLIC_BASE_URL || `https://${request.headers.host}`
  return new URL(relativePath, baseUrl).toString()
}

async function dispatchPbixWorkflow({ jobId, pbipPackageUrl }) {
  const owner = process.env.GITHUB_OWNER
  const repo = process.env.GITHUB_REPO
  const token = process.env.GITHUB_TOKEN
  const ref = process.env.GITHUB_REF || 'main'
  if (!owner || !repo || !token) {
    return { dispatched: false, reason: 'Missing GITHUB_OWNER, GITHUB_REPO, or GITHUB_TOKEN environment variables' }
  }

  const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/actions/workflows/package-pbix.yml/dispatches`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      ref,
      inputs: {
        job_id: jobId,
        pbip_package_url: pbipPackageUrl,
        callback_url: process.env.PBIX_CALLBACK_URL || '',
        callback_token: process.env.PBIX_CALLBACK_TOKEN || '',
      },
    }),
  })

  if (!response.ok) {
    return { dispatched: false, reason: `GitHub workflow dispatch failed: ${response.status} ${await response.text()}` }
  }
  return { dispatched: true, workflow: 'package-pbix.yml', ref }
}

function sendJson(response, status, payload) {
  response.statusCode = status
  response.setHeader('Content-Type', 'application/json')
  response.end(JSON.stringify(payload))
}

async function parseMultipartUpload(request) {
  const chunks = []
  for await (const chunk of request) chunks.push(chunk)
  const body = Buffer.concat(chunks)
  const contentType = request.headers['content-type'] || ''
  const boundary = contentType.match(/boundary=(.+)$/)?.[1]
  if (!boundary) throw new Error('Missing multipart boundary')
  const boundaryBuffer = Buffer.from(`--${boundary}`)
  const parts = []
  let start = body.indexOf(boundaryBuffer) + boundaryBuffer.length + 2
  while (start > boundaryBuffer.length) {
    const end = body.indexOf(boundaryBuffer, start)
    if (end === -1) break
    const part = body.subarray(start, end - 2)
    const headerEnd = part.indexOf(Buffer.from('\r\n\r\n'))
    if (headerEnd !== -1) {
      const headers = part.subarray(0, headerEnd).toString('utf8')
      const data = part.subarray(headerEnd + 4)
      parts.push({ headers, data })
    }
    start = end + boundaryBuffer.length + 2
  }
  const filePart = parts.find((part) => /name="workbook"/.test(part.headers))
  if (!filePart) throw new Error('No workbook file uploaded')
  const filename = filePart.headers.match(/filename="([^"]+)"/)?.[1] || 'upload.twbx'
  return { filename, data: filePart.data }
}

async function handleConvert(request, response) {
  const upload = await parseMultipartUpload(request)
  const jobId = crypto.randomUUID()
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), `altimate-migrator-${jobId}-`))
  const extension = path.extname(upload.filename) || '.twbx'
  const workbookPath = path.join(tempDir, `source${extension}`)
  fs.writeFileSync(workbookPath, upload.data)

  const { ast: tableauAst, summary } = extractTableauAst(workbookPath)
  const powerbiAst = powerBiAstFromTableau(tableauAst)
  const validationRows = compareAsts(tableauAst, powerbiAst)
  const validationCsv = toCsv(validationRows)
  const { buffer, migrationSpec } = createPbipPackage({ jobId, originalName: upload.filename, tableauAst, powerbiAst, validationCsv })
  packages.set(jobId, { buffer, filename: 'powerbi_project_package.zip' })

  const statusSummary = validationRows.reduce((acc, row) => {
    acc[row.status] = (acc[row.status] || 0) + 1
    return acc
  }, {})
  const pbipPackagePath = `/api/downloads/${jobId}/powerbi_project_package.zip`
  const metadata = {
    jobId,
    status: 'pbip-generated',
    pbipPackagePath,
    pbipPackageUrl: absoluteUrl(request, pbipPackagePath),
    pbix: null,
    workflow: null,
    updatedAt: new Date().toISOString(),
  }
  jobs.set(jobId, metadata)

  sendJson(response, 200, {
    jobId,
    workbookName: tableauAst.workbook.name,
    originalFile: upload.filename,
    extractionSummary: summary,
    validationSummary: {
      total: validationRows.length,
      pass: statusSummary.Pass || 0,
      warning: statusSummary.Warning || 0,
      fail: statusSummary.Fail || 0,
    },
    rows: validationRows,
    downloads: {
      tableauAst: `/api/downloads/${jobId}/tableau_ast.json`,
      powerbiAst: `/api/downloads/${jobId}/powerbi_ast.json`,
      validationCsv: `/api/downloads/${jobId}/validation_results.csv`,
      pbipPackage: pbipPackagePath,
      migrationPackage: pbipPackagePath,
      pbix: null,
    },
    migrationSpec,
  })
}

export default async function handler(request, response) {
  try {
    const url = new URL(request.url, `https://${request.headers.host}`)
    const pathname = url.pathname

    if (request.method === 'GET' && pathname === '/api/health') {
      sendJson(response, 200, { ok: true, service: 'tableau-powerbi-validator-api' })
      return
    }

    if (request.method === 'POST' && pathname === '/api/convert') {
      await handleConvert(request, response)
      return
    }

    const downloadMatch = pathname.match(/^\/api\/downloads\/([^/]+)\/([^/]+)$/)
    if (request.method === 'GET' && downloadMatch) {
      const [, jobId, filename] = downloadMatch
      const packageEntry = packages.get(jobId)
      if (!packageEntry) {
        sendJson(response, 404, { error: 'Download expired or job not found' })
        return
      }
      response.setHeader('Content-Type', filename.endsWith('.zip') ? 'application/zip' : 'application/octet-stream')
      response.setHeader('Content-Disposition', `attachment; filename="${filename}"`)
      response.end(packageEntry.buffer)
      return
    }

    const jobMatch = pathname.match(/^\/api\/jobs\/([^/]+)$/)
    if (request.method === 'GET' && jobMatch) {
      const metadata = jobs.get(jobMatch[1])
      if (!metadata) {
        sendJson(response, 404, { error: 'Job not found in this server process' })
        return
      }
      sendJson(response, 200, metadata)
      return
    }

    const dispatchMatch = pathname.match(/^\/api\/jobs\/([^/]+)\/package-pbix$/)
    if (request.method === 'POST' && dispatchMatch) {
      const metadata = jobs.get(dispatchMatch[1])
      if (!metadata) {
        sendJson(response, 404, { error: 'Job not found in this server process' })
        return
      }
      const dispatch = await dispatchPbixWorkflow({ jobId: metadata.jobId, pbipPackageUrl: metadata.pbipPackageUrl })
      metadata.status = dispatch.dispatched ? 'pbix-worker-dispatched' : 'pbix-worker-unavailable'
      metadata.workflow = dispatch
      metadata.updatedAt = new Date().toISOString()
      jobs.set(metadata.jobId, metadata)
      sendJson(response, dispatch.dispatched ? 202 : 200, metadata)
      return
    }

    sendJson(response, 404, { error: 'Not found' })
  } catch (error) {
    sendJson(response, 500, { error: error.message || 'Unexpected server error' })
  }
}

export const config = {
  api: {
    bodyParser: false,
  },
}
